-- AlterTable
ALTER TABLE `Customer` MODIFY `address` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `zip` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `city` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `state` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `country` VARCHAR(191) NOT NULL DEFAULT '';

-- AlterTable
ALTER TABLE `Property` MODIFY `country` VARCHAR(191) NOT NULL DEFAULT '';
